pipeline {
    agent any
    
    tools {
         jdk 'jdk17'
         gradle 'gradle'
         git 'git'
    }
    stages {
         stage ('checkout from scm') {
            steps {
                git 'https://github.com/Utk2022/gradle-workspace.git'
            }
        }
         stage ('build gradle') {
            steps {
              dir ('CalculatorProject') {
                sh './gradlew compilejava'
                sh './gradlew tasks'
                sh './gradlew build' 
                sh './gradlew test'
               }
            }
        }
        stage ('sonarqube analysis') {
            steps {
              dir ('CalculatorProject') {    
                script {
                    withSonarQubeEnv(credentialsId: 'sonar-token') {
                        sh './gradlew sonar -Dsonar.projectKey=gradle-java-calculator-application -Dsonar.host.url=http://172.16.8.10:9000 -Dsonar.login=sqp_447f58385e9c3598334f7d33c1ed5a0e57195ccc'
                   }
                   // quality gate
                  // timeout(time: 5, unit: 'MINUTES'){
                    //   def qg = waitForQualityGate()
                      // if(qg.status != 'OK'){
                        //   error "pipeline is aborted due to quality gate failure: ${qg.status}"
                          
                      // } 
                   //}
                 }
            }
        }
        
       }
        stage ('Upload build artifacts') {
          steps {
              dir ('CalculatorProject') {
                  sh 'aws s3 cp app/build/libs/app.jar s3://jar-directory-calculator-1234567891011/app_$BUILD_ID.jar'
              
          }
      }
    }
    
        stage ('checkout') {
            steps {
                git 'https://github.com/Utk2022/gradle-workspace.git'
            }
    }
    
      stage('Cleanws') {
        steps {
            CleanWs()
        }
        
    }
   }
}

